### ISSUE TITLE
Awareness of Domain-Knowledge, Problem Solving vs. "fancy algorithms"

### ISSUE THREAD

**Issue by MerlinSchaefer** [TechLabs-Berlin/data-science-accelerator#6]
We want to make the learners aware of the importance of **really** understanding your problem and trying to **solve** it using domain knowledge and thinking, rather than just trying to use fancy techniques.

Still need Content.

I could make a short video/text and talk about the topic

**Comment by valiantone** [comment]
This is definitely needed, a video reduces the need for lengthy text. 👍🏽  for idea!
yes please merlin, go ahead and take this one!
